wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1701415616.32457
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.7.10
      5: 0.13.7
      8:
      - 5
batch_size:
  desc: null
  value: 4
dataset:
  desc: null
  value: siim
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
lrs:
  desc: null
  value: 'true'
lrs_min:
  desc: null
  value: 0.0
mgpu:
  desc: null
  value: 'false'
root:
  desc: null
  value: /code/fcbformer/zhou/originalfile/SIIM-ACR-Pneumothorax-Seg-XR/
